refactor: 7711 minor tidyup of SNS package
Ensono/stacks-dotnet pull request #471
Opened 2024-08-30 08:47 UTC by sharonrussell

#### 📲 What

Removing code smells/warnings and minor tidyup

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

2024-08-30 08:51 UTC, alexanderwjrussell approved these changes
Looks fine to me

2024-08-30 13:52 UTC, alexanderwjrussell commented on src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDbMenuRepositoryTests.cs
> +/// of MenuRepository against the data store at development\integration
Good spot!

2024-08-30 13:53 UTC, alexanderwjrussell approved these changes
Looks good!

2024-08-30 13:54 UTC, chris31389 commented
Does the template need updating to include or exclude the test files based on the input?

2024-08-30 14:37 UTC, alexanderwjrussell commented
/azp run

2024-09-02 11:00 UTC, chris31389 requested changes

2024-09-02 11:02 UTC, sharonrussell commented on src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.AWS.SNS/Publisher/EventPublisher.cs
> +            catch (AmazonSimpleNotificationServiceException? exception)
Good spot, will reverse

2024-09-02 11:02 UTC, sharonrussell commented on src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.AWS.SNS/Logging/LogDefinition.cs
> +        private static void LogException(ILogger logger, Exception? exception)
Will reverse

2024-09-02 11:02 UTC, sharonrussell commented on src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.AWS.SNS/Logging/LogDefinition.cs
>              LogException(logger, ex);
Will reverse

2024-09-02 11:03 UTC, sharonrussell commented on src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.AWS.SNS/AwsSnsConfiguration.cs
> +    public Secret TopicArn { get; init; } = null!;
I brought this across as-is without considering a refactor - would you recommend one?

2024-09-02 11:03 UTC, sharonrussell commented on src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.CQRS/xxENSONOxx.xxSTACKSxx.CQRS.csproj
> +        <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.7.400.5" />
Will take a look

2024-09-02 13:15 UTC, sharonrussell commented on src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.AWS.SNS/AwsSnsConfiguration.cs
> +    public Secret TopicArn { get; init; } = null!;
I think we should change this in a future piece of work considering it would be a breaking change

2024-09-02 16:07 UTC, chris31389 approved these changes

2024-09-02 16:10 UTC, merged